#!/bin/sh

set -e

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 </full/path/to/dir/or/file>"
  exit 1
fi

json=$(cat .env.json)

docker build -t 18fgsa/s3-resource-simple .

echo $json | docker run \
  -i \
  --rm \
  -v $source:/tmp/input \
  18fgsa/s3-resource-simple \
  /opt/resource/out /tmp/input
